"""
Django settings for apied_service project.

Generated by 'django-admin startproject' using Django 5.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from pathlib import Path
from decouple import config # Required for secure environment variables

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Fetch SECRET_KEY from environment (e.g., a .env file)
SECRET_KEY = config('SECRET_KEY', default="django-insecure-cf2^l!%-ct06bc$dy!-p!2+863r@-^b^a(e24ie#3bz4ias$=w")

# SECURITY WARNING: don't run with debug turned on in production!
# Fetch DEBUG status from environment, defaulting to False in production
DEBUG = config('DEBUG', default=False, cast=bool)

# Add all domains this service will run on
ALLOWED_HOSTS = ['gloex.pythonanywhere.com', '127.0.0.1', 'localhost', 'www.gloex.org', 'gloex.org']

# settings.py on the gloex.pythonanywhere.com server

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party apps
    'corsheaders', # Required for cross-origin requests

    # Local app
    'apied',
]

MIDDLEWARE = [
    # CORS Middleware MUST be placed very high up, before common middleware
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # CSRF is left here but its functionality is managed by CORS/Session cookies below
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "apied_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "apied_service.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
MEDIA_ROOT = '/home/gloex/apied_service/media'
MEDIA_URL = '/media/'
STATIC_ROOT = '/home/gloex/apied_service/static'
# STATIC_URL is defined above but we keep the root defined for deployment


# --- CORS and Session Configuration (CRITICAL for Cross-Origin API) ---

# settings.py on the gloex.pythonanywhere.com server

CORS_ALLOWED_ORIGINS = [
    # Existing origins...
    "https://gloex.pythonanywhere.com",
    "http://127.0.0.1:8000",

    # ADD YOUR NEW VPS DOMAIN HERE (use HTTPS if your VPS is secured)
    "https://gloex.org",
    "https://www.gloex.org",
]

# This MUST be True to allow the browser to send cookies (like session ID) cross-origin
CORS_ALLOW_CREDENTIALS = True

# Ensure cookies work cross-origin (needed for session/cookie auth)
# Setting SAMESITE to 'None' and SECURE to True is required for cross-site cookie transmission over HTTPS.
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True
