# Generated by Django 5.1.3 on 2025-10-02 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "project_url",
                    models.URLField(max_length=500, verbose_name="Project Link"),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("repo", "Code Repository (e.g., GitHub)"),
                            ("demo", "Live Demo Site (e.g., Netlify, Vercel)"),
                            ("image", "Public Image Link (e.g., Imgur)"),
                            ("custom", "Custom Link"),
                        ],
                        default="repo",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who posted this project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Post",
                "verbose_name_plural": "Project Posts",
                "ordering": ["-created_at"],
            },
        ),
    ]
