# Generated by Django 5.2.7 on 2025-10-02 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apied", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpost",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="If unchecked, only you can see it on your portfolio.",
                verbose_name="Publicly Visible",
            ),
        ),
        migrations.AddField(
            model_name="projectpost",
            name="screenshot",
            field=models.ImageField(
                blank=True,
                help_text="Upload a screenshot of the project.",
                null=True,
                upload_to="project_screenshots/",
            ),
        ),
        migrations.AddField(
            model_name="projectpost",
            name="screenshot_url_fallback",
            field=models.URLField(
                blank=True,
                help_text="A direct URL to a public image if no file is uploaded.",
                max_length=500,
                null=True,
                verbose_name="Fallback Image Link",
            ),
        ),
        migrations.AddField(
            model_name="projectpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="projectpost",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="projectpost",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("frontend", "Frontend Development (e.g., React, Vue, HTML/CSS)"),
                    ("backend", "Backend Development (e.g., Django, Node.js, Flask)"),
                    ("fullstack", "Full-Stack Application"),
                    ("mobile", "Mobile Application (e.g., Android, iOS, Flutter)"),
                    ("design", "UI/UX Design"),
                    ("other", "Other"),
                ],
                default="fullstack",
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="projectpost",
            name="project_url",
            field=models.URLField(max_length=500, verbose_name="Demo/Primary Link"),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="apied.projectpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "resource_url",
                    models.URLField(max_length=500, verbose_name="Resource Link"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="apied.projectpost",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="apied.projectpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Like",
                "verbose_name_plural": "Likes",
                "unique_together": {("project", "user")},
            },
        ),
    ]
