# Generated by Django 5.1.3 on 2025-10-03 13:03

import apied.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apied", "0003_projectpost_custom_field_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_code",
                    models.CharField(
                        default=apied.models.generate_request_code,
                        editable=False,
                        max_length=8,
                        unique=True,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("build_idea", "Build Your Idea"),
                            ("build_website", "Build a Website"),
                            ("build_software", "Build Software"),
                            ("cybersecurity", "Cybersecurity Services"),
                            ("training", "Training"),
                            ("team_management", "Team Management"),
                            ("join_us", "Join Us"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("company", "Company/Organization"),
                            ("individual", "Individual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        help_text="Your company or your full name", max_length=255
                    ),
                ),
                ("preferred_language", models.CharField(max_length=50)),
                (
                    "job_category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., E-commerce, Portfolio, ERP System",
                        max_length=100,
                    ),
                ),
                ("job_description", models.TextField()),
                (
                    "job_attachment_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to a document or image (e.g., Google Drive, Dropbox)",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("primary_phone", models.CharField(max_length=20)),
                ("secondary_phone", models.CharField(blank=True, max_length=20)),
                ("primary_email", models.EmailField(max_length=254)),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("below_20k", "Below 20,000 RWF"),
                            ("20k_50k", "20,000 - 50,000 RWF"),
                            ("50k_100k", "50,000 - 100,000 RWF"),
                            ("100k_200k", "100,000 - 200,000 RWF"),
                            ("200k_500k", "200,000 - 500,000 RWF"),
                            ("above_500k", "Above 500,000 RWF"),
                        ],
                        max_length=20,
                    ),
                ),
                ("terms_accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request",
                "verbose_name_plural": "Service Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="apied.servicerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
