# Generated by Django 5.2.7 on 2025-10-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apied", "0004_servicerequest_adminreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The name of the service or package.", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A short explanation of what the service includes.",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        help_text="The price, e.g., '150,000 RWF' or 'Contact Us'.",
                        max_length=50,
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(
                        help_text="The URL to redirect to when this tariff is clicked.",
                        max_length=500,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366F1",
                        help_text="Hex color code for the tariff display (e.g., #6366F1).",
                        max_length=7,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers show up first).",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this to hide the tariff from the public view.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tariff",
                "verbose_name_plural": "Tariffs",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
