# Generated by Django 5.2.7 on 2025-10-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apied", "0002_projectpost_is_public_projectpost_screenshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpost",
            name="custom_field_name",
            field=models.CharField(
                blank=True,
                help_text="Optional: A label for an extra piece of information (e.g., 'Tech Stack').",
                max_length=50,
                null=True,
                verbose_name="Custom Field Label",
            ),
        ),
        migrations.AddField(
            model_name="projectpost",
            name="custom_field_value",
            field=models.TextField(
                blank=True,
                help_text="Optional: The content for your custom field (e.g., 'Django, React, PostgreSQL').",
                null=True,
                verbose_name="Custom Field Content",
            ),
        ),
        migrations.AddField(
            model_name="projectpost",
            name="source_code_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the GitHub repository or source code download.",
                max_length=500,
                null=True,
                verbose_name="Source Code Link",
            ),
        ),
        migrations.AlterField(
            model_name="projectpost",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("frontend", "Frontend Development"),
                    ("backend", "Backend Development"),
                    ("fullstack", "Full-Stack Application"),
                    ("mobile", "Mobile Application"),
                    ("design", "UI/UX Design"),
                    ("other", "Other"),
                ],
                default="fullstack",
                max_length=20,
                verbose_name="Category",
            ),
        ),
    ]
